spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/planapp?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
      username: toot
      password: giyoyo9420
      driver-class-name: com.mysql.cj.jdbc.Driver